-- A copier dans Supabase > SQL Editor > New query > Run.
-- Script relancable : comptes, profils, avatars, salons publics/prives, amis et DM.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null check (char_length(pseudo) between 3 and 20),
  email text not null,
  title text not null default 'Nouveau joueur' check (char_length(title) between 1 and 32),
  status text not null default 'En ligne' check (char_length(status) between 1 and 32),
  bio text not null default '' check (char_length(bio) <= 240),
  website text not null default '' check (website = '' or website ~ '^https://[^[:space:]]+$'),
  avatar_color text not null default '#39ff88' check (avatar_color ~ '^#[0-9A-Fa-f]{6}$'),
  avatar_url text not null default '' check (avatar_url = '' or avatar_url ~ '^https://[^[:space:]]+$'),
  name_style text not null default 'solid' check (name_style in ('solid', 'gradient', 'rainbow')),
  name_color_a text not null default '#39ff88' check (name_color_a ~ '^#[0-9A-Fa-f]{6}$'),
  name_color_b text not null default '#ffdc5e' check (name_color_b ~ '^#[0-9A-Fa-f]{6}$'),
  last_seen timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists title text not null default 'Nouveau joueur';
alter table public.profiles add column if not exists status text not null default 'En ligne';
alter table public.profiles add column if not exists bio text not null default '';
alter table public.profiles add column if not exists website text not null default '';
alter table public.profiles add column if not exists avatar_color text not null default '#39ff88';
alter table public.profiles add column if not exists avatar_url text not null default '';
alter table public.profiles add column if not exists name_style text not null default 'solid';
alter table public.profiles add column if not exists name_color_a text not null default '#39ff88';
alter table public.profiles add column if not exists name_color_b text not null default '#ffdc5e';
alter table public.profiles add column if not exists last_seen timestamptz;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.chat_rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 40),
  kind text not null default 'public' check (kind in ('public', 'private', 'dm')),
  owner_id uuid references auth.users(id) on delete set null,
  invite_code text unique not null default lower(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  created_at timestamptz not null default now()
);

create table if not exists public.room_members (
  room_id uuid not null references public.chat_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.chat_rooms(id) on delete cascade,
  user_id text not null,
  pseudo text not null check (char_length(pseudo) between 3 and 20),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.chat_messages add column if not exists room_id uuid references public.chat_rooms(id) on delete cascade;
alter table public.chat_messages replica identity full;

create table if not exists public.friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);

drop index if exists public.friend_requests_unique_pair_idx;

create unique index friend_requests_unique_pair_idx
on public.friend_requests (
  least(sender_id, receiver_id),
  greatest(sender_id, receiver_id)
)
where status in ('pending', 'accepted');

create table if not exists public.user_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  points integer not null default 0 check (points >= 0),
  total_points integer not null default 0 check (total_points >= 0),
  xp integer not null default 0 check (xp >= 0),
  level integer not null default 1 check (level >= 1),
  streak integer not null default 0 check (streak >= 0),
  last_daily_at date,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.point_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  xp_amount integer not null default 0,
  reason text not null,
  ref_id text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.shop_items (
  item_key text primary key,
  name text not null,
  description text not null,
  price integer not null check (price >= 0),
  item_type text not null default 'cosmetic',
  payload jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.shop_items (item_key, name, description, price, item_type, payload, sort_order)
values
  ('badge_founder', 'Badge Founder', 'Badge rare affiche dans ton inventaire.', 500, 'badge', '{"badge":"Founder"}', 10),
  ('name_gold', 'Pseudo Gold', 'Couleur de pseudo or pour flex.', 350, 'name_style', '{"name_style":"gradient","name_color_a":"#ffdc5e","name_color_b":"#fb923c"}', 20),
  ('name_rainbow_plus', 'Pseudo Rainbow+', 'Style arc-en-ciel premium.', 850, 'name_style', '{"name_style":"rainbow"}', 30),
  ('avatar_frame_neon', 'Frame Neon', 'Cadre neon pour ta photo de profil.', 450, 'avatar_frame', '{"frame":"neon"}', 40),
  ('theme_blueprint', 'Theme Blueprint', 'Theme bleu pour ton interface locale.', 250, 'theme', '{"theme":"blue"}', 50),
  ('theme_goldrush', 'Theme Gold Rush', 'Theme or pour ton interface locale.', 250, 'theme', '{"theme":"gold"}', 60)
on conflict (item_key) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  item_type = excluded.item_type,
  payload = excluded.payload,
  is_active = true,
  sort_order = excluded.sort_order;

create table if not exists public.user_inventory (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  item_key text not null references public.shop_items(item_key) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  equipped boolean not null default false,
  acquired_at timestamptz not null default now(),
  unique (user_id, item_key)
);

create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_key text not null,
  score integer not null default 0,
  reward_points integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.game_duels (
  id uuid primary key default gen_random_uuid(),
  code text unique not null default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)),
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete cascade,
  host_choice text check (host_choice in ('rock', 'paper', 'scissors')),
  guest_choice text check (guest_choice in ('rock', 'paper', 'scissors')),
  winner_id uuid references auth.users(id) on delete set null,
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'done')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.chat_rooms (id, name, kind, owner_id, invite_code)
values ('00000000-0000-4000-8000-000000000001', 'General', 'public', null, 'general')
on conflict (id) do nothing;

update public.chat_messages
set room_id = '00000000-0000-4000-8000-000000000001'
where room_id is null;

alter table public.chat_messages alter column room_id set not null;

alter table public.profiles enable row level security;
alter table public.chat_rooms enable row level security;
alter table public.room_members enable row level security;
alter table public.chat_messages enable row level security;
alter table public.friend_requests enable row level security;
alter table public.user_wallets enable row level security;
alter table public.point_ledger enable row level security;
alter table public.shop_items enable row level security;
alter table public.user_inventory enable row level security;
alter table public.game_scores enable row level security;
alter table public.game_duels enable row level security;

drop policy if exists "Avatars publics lisibles" on storage.objects;
drop policy if exists "Les utilisateurs ajoutent leur avatar" on storage.objects;
drop policy if exists "Les utilisateurs modifient leur avatar" on storage.objects;
drop policy if exists "Les utilisateurs suppriment leur avatar" on storage.objects;

create policy "Avatars publics lisibles"
on storage.objects
for select
to public
using (bucket_id = 'avatars');

create policy "Les utilisateurs ajoutent leur avatar"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Les utilisateurs modifient leur avatar"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Les utilisateurs suppriment leur avatar"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create or replace function public.room_is_public(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.chat_rooms cr
    where cr.id = target_room
      and cr.kind = 'public'
  );
$$;

create or replace function public.current_user_is_room_member(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.room_members rm
    where rm.room_id = target_room
      and rm.user_id = auth.uid()
  );
$$;

create or replace function public.current_user_is_room_owner(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.chat_rooms cr
    where cr.id = target_room
      and cr.owner_id = auth.uid()
  );
$$;

create or replace function public.current_user_can_read_room(target_room uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.room_is_public(target_room)
    or public.current_user_is_room_member(target_room)
    or public.current_user_is_room_owner(target_room);
$$;

drop policy if exists "Les utilisateurs lisent leur profil" on public.profiles;
drop policy if exists "Les utilisateurs creent leur profil" on public.profiles;
drop policy if exists "Les utilisateurs modifient leur profil" on public.profiles;
drop policy if exists "Les profils publics sont lisibles" on public.profiles;
drop policy if exists "Les utilisateurs creent leur profil" on public.profiles;
drop policy if exists "Les utilisateurs modifient leur profil" on public.profiles;

create policy "Les profils publics sont lisibles"
on public.profiles
for select
to authenticated
using (true);

create policy "Les utilisateurs creent leur profil"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "Les utilisateurs modifient leur profil"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Les salons visibles sont lisibles" on public.chat_rooms;
drop policy if exists "Les utilisateurs creent des salons" on public.chat_rooms;
drop policy if exists "Les proprietaires modifient leurs salons" on public.chat_rooms;

create policy "Les salons visibles sont lisibles"
on public.chat_rooms
for select
to authenticated
using (
  kind = 'public'
  or owner_id = auth.uid()
  or public.current_user_is_room_member(id)
);

create policy "Les utilisateurs creent des salons"
on public.chat_rooms
for insert
to authenticated
with check (owner_id = auth.uid());

create policy "Les proprietaires modifient leurs salons"
on public.chat_rooms
for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "Les membres voient les membres" on public.room_members;
drop policy if exists "Les membres rejoignent un salon public" on public.room_members;
drop policy if exists "Les proprietaires ajoutent des membres" on public.room_members;

create policy "Les membres voient les membres"
on public.room_members
for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_user_is_room_owner(room_id)
  or public.current_user_is_room_member(room_id)
);

create policy "Les membres rejoignent un salon public"
on public.room_members
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.room_is_public(room_id)
);

create policy "Les proprietaires ajoutent des membres"
on public.room_members
for insert
to authenticated
with check (public.current_user_is_room_owner(room_id));

drop policy if exists "Tout le monde peut lire le tchat" on public.chat_messages;
drop policy if exists "Les visiteurs peuvent envoyer un message" on public.chat_messages;
drop policy if exists "Les utilisateurs connectes lisent le tchat" on public.chat_messages;
drop policy if exists "Les utilisateurs connectes envoient un message" on public.chat_messages;
drop policy if exists "Les membres lisent les messages du salon" on public.chat_messages;
drop policy if exists "Les membres envoient dans le salon" on public.chat_messages;
drop policy if exists "Les utilisateurs suppriment leurs messages" on public.chat_messages;

create policy "Les membres lisent les messages du salon"
on public.chat_messages
for select
to authenticated
using (public.current_user_can_read_room(room_id));

create policy "Les membres envoient dans le salon"
on public.chat_messages
for insert
to authenticated
with check (
  user_id = auth.uid()::text
  and char_length(pseudo) between 3 and 20
  and char_length(content) between 1 and 500
  and public.current_user_can_read_room(room_id)
);

create policy "Les utilisateurs suppriment leurs messages"
on public.chat_messages
for delete
to authenticated
using (user_id = auth.uid()::text);

drop policy if exists "Les demandes visibles sont lisibles" on public.friend_requests;
drop policy if exists "Les utilisateurs envoient des demandes" on public.friend_requests;
drop policy if exists "Le receveur repond aux demandes" on public.friend_requests;

create policy "Les demandes visibles sont lisibles"
on public.friend_requests
for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

create policy "Les utilisateurs envoient des demandes"
on public.friend_requests
for insert
to authenticated
with check (sender_id = auth.uid() and sender_id <> receiver_id);

create policy "Le receveur repond aux demandes"
on public.friend_requests
for update
to authenticated
using (receiver_id = auth.uid())
with check (receiver_id = auth.uid());

drop policy if exists "Les utilisateurs lisent leur wallet" on public.user_wallets;
drop policy if exists "Les utilisateurs lisent leur historique points" on public.point_ledger;
drop policy if exists "Les items actifs sont lisibles" on public.shop_items;
drop policy if exists "Les utilisateurs lisent leur inventaire" on public.user_inventory;
drop policy if exists "Les scores sont lisibles" on public.game_scores;
drop policy if exists "Les duels participants sont lisibles" on public.game_duels;

create policy "Les utilisateurs lisent leur wallet"
on public.user_wallets
for select
to authenticated
using (user_id = auth.uid());

create policy "Les utilisateurs lisent leur historique points"
on public.point_ledger
for select
to authenticated
using (user_id = auth.uid());

create policy "Les items actifs sont lisibles"
on public.shop_items
for select
to authenticated
using (is_active);

create policy "Les utilisateurs lisent leur inventaire"
on public.user_inventory
for select
to authenticated
using (user_id = auth.uid());

create policy "Les scores sont lisibles"
on public.game_scores
for select
to authenticated
using (true);

create policy "Les duels participants sont lisibles"
on public.game_duels
for select
to authenticated
using (host_id = auth.uid() or guest_id = auth.uid());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_pseudo text;
begin
  requested_pseudo := nullif(trim(new.raw_user_meta_data->>'pseudo'), '');

  insert into public.profiles (id, pseudo, email)
  values (
    new.id,
    coalesce(requested_pseudo, 'Player_' || left(new.id::text, 8)),
    coalesce(new.email, '')
  )
  on conflict (id) do update
  set
    pseudo = excluded.pseudo,
    email = excluded.email,
    last_seen = now(),
    updated_at = now();

  insert into public.room_members (room_id, user_id, role)
  values ('00000000-0000-4000-8000-000000000001', new.id, 'member')
  on conflict do nothing;

  insert into public.user_wallets (user_id)
  values (new.id)
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.join_room_by_code(room_code text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_room uuid;
begin
  select id
  into target_room
  from public.chat_rooms
  where invite_code = lower(trim(room_code))
    and kind in ('private', 'public')
  limit 1;

  if target_room is null then
    raise exception 'room_not_found';
  end if;

  insert into public.room_members (room_id, user_id, role)
  values (target_room, auth.uid(), 'member')
  on conflict do nothing;

  return target_room;
end;
$$;

create or replace function public.create_or_get_dm(friend_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_room uuid;
  new_room uuid;
begin
  if friend_id = auth.uid() then
    raise exception 'invalid_friend';
  end if;

  if not exists (
    select 1
    from public.friend_requests fr
    where fr.status = 'accepted'
      and (
        (fr.sender_id = auth.uid() and fr.receiver_id = friend_id)
        or (fr.sender_id = friend_id and fr.receiver_id = auth.uid())
      )
  ) then
    raise exception 'not_friends';
  end if;

  select rm1.room_id
  into existing_room
  from public.room_members rm1
  join public.room_members rm2 on rm2.room_id = rm1.room_id
  join public.chat_rooms cr on cr.id = rm1.room_id
  where cr.kind = 'dm'
    and rm1.user_id = auth.uid()
    and rm2.user_id = friend_id
  limit 1;

  if existing_room is not null then
    return existing_room;
  end if;

  insert into public.chat_rooms (name, kind, owner_id)
  values ('DM', 'dm', auth.uid())
  returning id into new_room;

  insert into public.room_members (room_id, user_id, role)
  values
    (new_room, auth.uid(), 'owner'),
    (new_room, friend_id, 'member')
  on conflict do nothing;

  return new_room;
end;
$$;

create or replace function public.ensure_wallet(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_user is null then
    raise exception 'missing_user';
  end if;

  insert into public.user_wallets (user_id)
  values (target_user)
  on conflict (user_id) do nothing;
end;
$$;

create or replace function public.add_points(
  target_user uuid,
  point_delta integer,
  xp_delta integer,
  reason_text text,
  ref_text text default ''
)
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_points integer;
  safe_xp integer;
  updated_wallet public.user_wallets;
begin
  safe_points := greatest(least(coalesce(point_delta, 0), 10000), -100000);
  safe_xp := greatest(least(coalesce(xp_delta, 0), 10000), -100000);

  perform public.ensure_wallet(target_user);

  update public.user_wallets
  set
    points = greatest(0, points + safe_points),
    total_points = total_points + greatest(safe_points, 0),
    xp = greatest(0, xp + safe_xp),
    level = greatest(1, floor(sqrt(greatest(0, xp + safe_xp)::double precision / 120.0))::integer + 1),
    updated_at = now()
  where user_id = target_user
  returning * into updated_wallet;

  insert into public.point_ledger (user_id, amount, xp_amount, reason, ref_id)
  values (target_user, safe_points, safe_xp, coalesce(reason_text, 'points'), coalesce(ref_text, ''));

  return updated_wallet;
end;
$$;

create or replace function public.get_my_wallet()
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet public.user_wallets;
begin
  perform public.ensure_wallet(auth.uid());

  select *
  into wallet
  from public.user_wallets
  where user_id = auth.uid();

  return wallet;
end;
$$;

create or replace function public.claim_daily_reward()
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  wallet public.user_wallets;
  new_streak integer;
  reward integer;
begin
  perform public.ensure_wallet(auth.uid());

  select *
  into wallet
  from public.user_wallets
  where user_id = auth.uid()
  for update;

  if wallet.last_daily_at = current_date then
    raise exception 'daily_already_claimed';
  end if;

  if wallet.last_daily_at = current_date - 1 then
    new_streak := wallet.streak + 1;
  else
    new_streak := 1;
  end if;

  reward := 100 + least(new_streak, 7) * 20;

  update public.user_wallets
  set last_daily_at = current_date,
      streak = new_streak,
      updated_at = now()
  where user_id = auth.uid();

  perform public.add_points(auth.uid(), reward, reward, 'daily', current_date::text);

  select *
  into wallet
  from public.user_wallets
  where user_id = auth.uid();

  return wallet;
end;
$$;

create or replace function public.complete_solo_game(game_key_input text, score_input integer)
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_game text;
  safe_score integer;
  reward integer;
  wallet public.user_wallets;
begin
  safe_game := lower(trim(coalesce(game_key_input, '')));
  safe_score := greatest(0, least(coalesce(score_input, 0), 100000));

  if safe_game not in ('reflex', 'memory', 'runner', 'aim', 'cipher') then
    raise exception 'invalid_game';
  end if;

  if exists (
    select 1
    from public.game_scores gs
    where gs.user_id = auth.uid()
      and gs.game_key = safe_game
      and gs.created_at > now() - interval '12 seconds'
  ) then
    raise exception 'game_cooldown';
  end if;

  reward := case safe_game
    when 'reflex' then least(90, greatest(8, floor(safe_score / 90.0)::integer))
    when 'memory' then least(120, greatest(10, floor(safe_score / 80.0)::integer))
    when 'runner' then least(140, greatest(10, floor(safe_score / 55.0)::integer))
    when 'aim' then least(130, greatest(10, floor(safe_score / 70.0)::integer))
    when 'cipher' then least(120, greatest(10, floor(safe_score / 80.0)::integer))
    else 10
  end;

  insert into public.game_scores (user_id, game_key, score, reward_points)
  values (auth.uid(), safe_game, safe_score, reward);

  wallet := public.add_points(auth.uid(), reward, reward * 2, 'game:' || safe_game, safe_score::text);
  return wallet;
end;
$$;

create or replace function public.purchase_shop_item(shop_key text)
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.shop_items;
  wallet public.user_wallets;
begin
  select *
  into item
  from public.shop_items
  where item_key = shop_key
    and is_active
  limit 1;

  if item.item_key is null then
    raise exception 'item_not_found';
  end if;

  if exists (
    select 1
    from public.user_inventory ui
    where ui.user_id = auth.uid()
      and ui.item_key = item.item_key
  ) then
    raise exception 'item_already_owned';
  end if;

  perform public.ensure_wallet(auth.uid());

  select *
  into wallet
  from public.user_wallets
  where user_id = auth.uid()
  for update;

  if wallet.points < item.price then
    raise exception 'not_enough_points';
  end if;

  wallet := public.add_points(auth.uid(), -item.price, 0, 'shop', item.item_key);

  insert into public.user_inventory (user_id, item_key, quantity)
  values (auth.uid(), item.item_key, 1)
  on conflict (user_id, item_key) do nothing;

  perform public.create_notification(auth.uid(), 'shop', 'Objet achete', item.name || ' ajoute a ton inventaire', jsonb_build_object('item_key', item.item_key));

  return wallet;
end;
$$;

create or replace function public.create_game_duel()
returns public.game_duels
language plpgsql
security definer
set search_path = public
as $$
declare
  duel public.game_duels;
begin
  perform public.ensure_wallet(auth.uid());

  insert into public.game_duels (host_id)
  values (auth.uid())
  returning * into duel;

  return duel;
end;
$$;

create or replace function public.join_game_duel(duel_code text)
returns public.game_duels
language plpgsql
security definer
set search_path = public
as $$
declare
  duel public.game_duels;
begin
  select *
  into duel
  from public.game_duels
  where code = upper(trim(duel_code))
    and status = 'waiting'
  for update;

  if duel.id is null then
    raise exception 'duel_not_found';
  end if;

  if duel.host_id = auth.uid() then
    raise exception 'duel_self_join';
  end if;

  update public.game_duels
  set guest_id = auth.uid(),
      status = 'playing',
      updated_at = now()
  where id = duel.id
  returning * into duel;

  perform public.ensure_wallet(auth.uid());
  return duel;
end;
$$;

create or replace function public.submit_duel_choice(duel_id uuid, choice_text text)
returns public.game_duels
language plpgsql
security definer
set search_path = public
as $$
declare
  duel public.game_duels;
  clean_choice text;
  winner uuid;
begin
  clean_choice := lower(trim(choice_text));

  if clean_choice not in ('rock', 'paper', 'scissors') then
    raise exception 'invalid_choice';
  end if;

  select *
  into duel
  from public.game_duels
  where id = duel_id
    and (host_id = auth.uid() or guest_id = auth.uid())
  for update;

  if duel.id is null then
    raise exception 'duel_not_found';
  end if;

  if duel.status = 'done' then
    return duel;
  end if;

  if duel.host_id = auth.uid() then
    update public.game_duels
    set host_choice = clean_choice,
        updated_at = now()
    where id = duel.id
    returning * into duel;
  elsif duel.guest_id = auth.uid() then
    update public.game_duels
    set guest_choice = clean_choice,
        updated_at = now()
    where id = duel.id
    returning * into duel;
  end if;

  if duel.host_choice is not null and duel.guest_choice is not null then
    winner := null;

    if duel.host_choice <> duel.guest_choice then
      if (duel.host_choice = 'rock' and duel.guest_choice = 'scissors')
        or (duel.host_choice = 'paper' and duel.guest_choice = 'rock')
        or (duel.host_choice = 'scissors' and duel.guest_choice = 'paper') then
        winner := duel.host_id;
      else
        winner := duel.guest_id;
      end if;
    end if;

    update public.game_duels
    set winner_id = winner,
        status = 'done',
        updated_at = now()
    where id = duel.id
    returning * into duel;

    if winner is null then
      perform public.add_points(duel.host_id, 8, 12, 'duel_draw', duel.id::text);
      perform public.add_points(duel.guest_id, 8, 12, 'duel_draw', duel.id::text);
    else
      perform public.add_points(winner, 35, 50, 'duel_win', duel.id::text);
      perform public.add_points(
        case when winner = duel.host_id then duel.guest_id else duel.host_id end,
        5,
        8,
        'duel_loss',
        duel.id::text
      );
    end if;
  end if;

  return duel;
end;
$$;

create or replace function public.award_chat_message_points()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.user_id ~* '^[0-9a-f-]{36}$' then
    perform public.add_points(new.user_id::uuid, 1, 1, 'chat_message', new.id::text);
  end if;

  return new;
end;
$$;

drop trigger if exists on_chat_message_points on public.chat_messages;

create trigger on_chat_message_points
after insert on public.chat_messages
for each row execute function public.award_chat_message_points();

insert into public.room_members (room_id, user_id, role)
select '00000000-0000-4000-8000-000000000001', id, 'member'
from auth.users
on conflict do nothing;

insert into public.user_wallets (user_id)
select id
from auth.users
on conflict do nothing;

create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);
create index if not exists chat_messages_room_created_idx on public.chat_messages (room_id, created_at desc);
create index if not exists chat_messages_user_id_idx on public.chat_messages (user_id);
create index if not exists room_members_user_idx on public.room_members (user_id);
create index if not exists room_members_room_idx on public.room_members (room_id);
create index if not exists chat_rooms_kind_idx on public.chat_rooms (kind);
create index if not exists friend_requests_sender_idx on public.friend_requests (sender_id);
create index if not exists friend_requests_receiver_idx on public.friend_requests (receiver_id);
create index if not exists point_ledger_user_created_idx on public.point_ledger (user_id, created_at desc);
create index if not exists user_inventory_user_idx on public.user_inventory (user_id);
create index if not exists game_scores_game_score_idx on public.game_scores (game_key, score desc);
create index if not exists game_scores_user_created_idx on public.game_scores (user_id, created_at desc);
create index if not exists game_duels_code_idx on public.game_duels (code);
create index if not exists game_duels_players_idx on public.game_duels (host_id, guest_id);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.chat_rooms to authenticated;
grant select, insert on public.room_members to authenticated;
grant select, insert, delete on public.chat_messages to authenticated;
grant select, insert, update on public.friend_requests to authenticated;
grant select on public.user_wallets to authenticated;
grant select on public.point_ledger to authenticated;
grant select on public.shop_items to authenticated;
grant select on public.user_inventory to authenticated;
grant select on public.game_scores to authenticated;
grant select on public.game_duels to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on function public.ensure_wallet(uuid) from public, anon, authenticated;
revoke all on function public.add_points(uuid, integer, integer, text, text) from public, anon, authenticated;
revoke all on function public.award_chat_message_points() from public, anon, authenticated;
revoke all on function public.join_room_by_code(text) from public, anon;
revoke all on function public.create_or_get_dm(uuid) from public, anon;
revoke all on function public.get_my_wallet() from public, anon;
revoke all on function public.claim_daily_reward() from public, anon;
revoke all on function public.complete_solo_game(text, integer) from public, anon;
revoke all on function public.purchase_shop_item(text) from public, anon;
revoke all on function public.create_game_duel() from public, anon;
revoke all on function public.join_game_duel(text) from public, anon;
revoke all on function public.submit_duel_choice(uuid, text) from public, anon;
grant execute on function public.room_is_public(uuid) to authenticated;
grant execute on function public.current_user_is_room_member(uuid) to authenticated;
grant execute on function public.current_user_is_room_owner(uuid) to authenticated;
grant execute on function public.current_user_can_read_room(uuid) to authenticated;
grant execute on function public.join_room_by_code(text) to authenticated;
grant execute on function public.create_or_get_dm(uuid) to authenticated;
grant execute on function public.get_my_wallet() to authenticated;
grant execute on function public.claim_daily_reward() to authenticated;
grant execute on function public.complete_solo_game(text, integer) to authenticated;
grant execute on function public.purchase_shop_item(text) to authenticated;
grant execute on function public.create_game_duel() to authenticated;
grant execute on function public.join_game_duel(text) to authenticated;
grant execute on function public.submit_duel_choice(uuid, text) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end;
$$;

do $$
begin
  alter publication supabase_realtime add table public.game_duels;
exception
  when duplicate_object then null;
  when undefined_object then null;
end;
$$;

-- Arcade v2 : missions, cosmetiques equipes, Aim/Code et Morpion multi.
alter table public.profiles add column if not exists avatar_frame text not null default 'none';
alter table public.profiles add column if not exists profile_theme text not null default 'default';

insert into public.shop_items (item_key, name, description, price, item_type, payload, sort_order)
values
  ('name_matrix', 'Pseudo Matrix', 'Degrade vert hacker pour ton pseudo.', 420, 'name_style', '{"name_style":"gradient","name_color_a":"#39ff88","name_color_b":"#7dd3fc"}', 70),
  ('avatar_frame_gold', 'Frame Gold', 'Cadre dore pour ta photo de profil.', 650, 'avatar_frame', '{"frame":"gold"}', 80)
on conflict (item_key) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  item_type = excluded.item_type,
  payload = excluded.payload,
  is_active = true,
  sort_order = excluded.sort_order;

create table if not exists public.user_missions (
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_key text not null,
  claimed_at timestamptz not null default now(),
  primary key (user_id, mission_key)
);

create table if not exists public.tic_tac_toe_games (
  id uuid primary key default gen_random_uuid(),
  code text unique not null default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)),
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete cascade,
  board text[] not null default array['','','','','','','','','']::text[],
  turn_id uuid references auth.users(id) on delete set null,
  winner_id uuid references auth.users(id) on delete set null,
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'done')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_missions enable row level security;
alter table public.tic_tac_toe_games enable row level security;

drop policy if exists "Les utilisateurs lisent leurs missions" on public.user_missions;
drop policy if exists "Les morpions participants sont lisibles" on public.tic_tac_toe_games;

create policy "Les utilisateurs lisent leurs missions"
on public.user_missions
for select
to authenticated
using (user_id = auth.uid());

create policy "Les morpions participants sont lisibles"
on public.tic_tac_toe_games
for select
to authenticated
using (host_id = auth.uid() or guest_id = auth.uid());

create or replace function public.equip_shop_item(shop_key text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.shop_items;
  owned public.user_inventory;
  profile public.profiles;
  frame_value text;
  theme_value text;
begin
  select *
  into item
  from public.shop_items
  where item_key = shop_key
    and is_active
  limit 1;

  if item.item_key is null then
    raise exception 'item_not_found';
  end if;

  select *
  into owned
  from public.user_inventory
  where user_id = auth.uid()
    and item_key = item.item_key;

  if owned.id is null then
    raise exception 'item_not_owned';
  end if;

  if item.item_type not in ('name_style', 'avatar_frame', 'theme') then
    raise exception 'item_not_equippable';
  end if;

  update public.user_inventory ui
  set equipped = false
  from public.shop_items si
  where ui.user_id = auth.uid()
    and ui.item_key = si.item_key
    and si.item_type = item.item_type;

  update public.user_inventory
  set equipped = true
  where user_id = auth.uid()
    and item_key = item.item_key;

  if item.item_type = 'name_style' then
    update public.profiles
    set name_style = coalesce(item.payload->>'name_style', 'solid'),
        name_color_a = coalesce(item.payload->>'name_color_a', '#39ff88'),
        name_color_b = coalesce(item.payload->>'name_color_b', '#ffdc5e'),
        updated_at = now()
    where id = auth.uid()
    returning * into profile;
  elsif item.item_type = 'avatar_frame' then
    frame_value := coalesce(item.payload->>'frame', 'none');
    if frame_value not in ('none', 'neon', 'gold') then
      frame_value := 'none';
    end if;

    update public.profiles
    set avatar_frame = frame_value,
        updated_at = now()
    where id = auth.uid()
    returning * into profile;
  elsif item.item_type = 'theme' then
    theme_value := coalesce(item.payload->>'theme', 'default');
    if theme_value not in ('default', 'blue', 'gold') then
      theme_value := 'default';
    end if;

    update public.profiles
    set profile_theme = theme_value,
        updated_at = now()
    where id = auth.uid()
    returning * into profile;
  end if;

  return profile;
end;
$$;

create or replace function public.get_my_missions()
returns table (
  mission_key text,
  label_text text,
  progress_value integer,
  goal_value integer,
  reward_points integer,
  claimed boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with stats as (
    select
      (select count(*)::integer from public.chat_messages where user_id = auth.uid()::text) as messages_count,
      (select count(*)::integer from public.game_scores where user_id = auth.uid()) as games_count,
      (select coalesce(max(score), 0)::integer from public.game_scores where user_id = auth.uid() and game_key = 'reflex') as best_reflex,
      (select coalesce(max(score), 0)::integer from public.game_scores where user_id = auth.uid() and game_key = 'aim') as best_aim,
      (select count(*)::integer from public.user_inventory where user_id = auth.uid()) as inventory_count,
      (select count(*)::integer from public.game_duels where (host_id = auth.uid() or guest_id = auth.uid()) and status = 'done')
        + (select count(*)::integer from public.tic_tac_toe_games where (host_id = auth.uid() or guest_id = auth.uid()) and status = 'done') as multi_count
  ), missions as (
    select 'first_message'::text as mission_key, 'Envoyer ton premier message'::text as label_text, messages_count as progress_value, 1::integer as goal_value, 60::integer as reward_points from stats
    union all select 'arcade_rookie', 'Finir 3 mini-jeux solo', games_count, 3, 120 from stats
    union all select 'reflex_1000', 'Faire 1000 points sur Reflex', best_reflex, 1000, 150 from stats
    union all select 'aim_1500', 'Faire 1500 points sur Aim Trainer', best_aim, 1500, 180 from stats
    union all select 'first_multi', 'Finir un match multijoueur', multi_count, 1, 140 from stats
    union all select 'first_shop', 'Acheter un item boutique', inventory_count, 1, 80 from stats
  )
  select
    missions.mission_key,
    missions.label_text,
    least(missions.progress_value, missions.goal_value),
    missions.goal_value,
    missions.reward_points,
    user_missions.user_id is not null as claimed
  from missions
  left join public.user_missions
    on user_missions.user_id = auth.uid()
   and user_missions.mission_key = missions.mission_key
  order by claimed, missions.reward_points;
$$;

create or replace function public.claim_mission(mission_key_input text)
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_key text;
  mission record;
  wallet public.user_wallets;
begin
  clean_key := lower(trim(coalesce(mission_key_input, '')));

  select *
  into mission
  from public.get_my_missions()
  where mission_key = clean_key;

  if not found then
    raise exception 'mission_not_found';
  end if;

  if mission.claimed then
    raise exception 'mission_already_claimed';
  end if;

  if mission.progress_value < mission.goal_value then
    raise exception 'mission_not_ready';
  end if;

  insert into public.user_missions (user_id, mission_key)
  values (auth.uid(), clean_key)
  on conflict do nothing;

  if not found then
    raise exception 'mission_already_claimed';
  end if;

  wallet := public.add_points(auth.uid(), mission.reward_points, mission.reward_points * 2, 'mission', clean_key);
  return wallet;
end;
$$;

create or replace function public.ttt_winner(board text[])
returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  wins integer[][] := array[[1,2,3],[4,5,6],[7,8,9],[1,4,7],[2,5,8],[3,6,9],[1,5,9],[3,5,7]];
  line integer[];
  mark text;
begin
  foreach line slice 1 in array wins loop
    mark := board[line[1]];
    if mark <> '' and mark = board[line[2]] and mark = board[line[3]] then
      return mark;
    end if;
  end loop;

  return '';
end;
$$;

create or replace function public.create_ttt_game()
returns public.tic_tac_toe_games
language plpgsql
security definer
set search_path = public
as $$
declare
  game public.tic_tac_toe_games;
begin
  perform public.ensure_wallet(auth.uid());

  insert into public.tic_tac_toe_games (host_id, turn_id)
  values (auth.uid(), auth.uid())
  returning * into game;

  return game;
end;
$$;

create or replace function public.join_ttt_game(game_code text)
returns public.tic_tac_toe_games
language plpgsql
security definer
set search_path = public
as $$
declare
  game public.tic_tac_toe_games;
begin
  select *
  into game
  from public.tic_tac_toe_games
  where code = upper(trim(game_code))
    and status = 'waiting'
  for update;

  if game.id is null then
    raise exception 'game_not_found';
  end if;

  if game.host_id = auth.uid() then
    raise exception 'game_self_join';
  end if;

  update public.tic_tac_toe_games
  set guest_id = auth.uid(),
      status = 'playing',
      turn_id = host_id,
      updated_at = now()
  where id = game.id
  returning * into game;

  perform public.ensure_wallet(auth.uid());
  return game;
end;
$$;

create or replace function public.play_ttt_move(game_id uuid, cell_index integer)
returns public.tic_tac_toe_games
language plpgsql
security definer
set search_path = public
as $$
declare
  game public.tic_tac_toe_games;
  new_board text[];
  symbol text;
  winner_symbol text;
  next_turn uuid;
  final_status text;
  final_winner uuid;
begin
  if cell_index < 0 or cell_index > 8 then
    raise exception 'invalid_cell';
  end if;

  select *
  into game
  from public.tic_tac_toe_games
  where id = game_id
    and (host_id = auth.uid() or guest_id = auth.uid())
  for update;

  if game.id is null then
    raise exception 'game_not_found';
  end if;

  if game.status = 'done' then
    return game;
  end if;

  if game.status <> 'playing' or game.guest_id is null then
    raise exception 'game_not_ready';
  end if;

  if game.turn_id <> auth.uid() then
    raise exception 'not_your_turn';
  end if;

  new_board := game.board;

  if coalesce(new_board[cell_index + 1], '') <> '' then
    raise exception 'cell_busy';
  end if;

  symbol := case when game.host_id = auth.uid() then 'X' else 'O' end;
  new_board[cell_index + 1] := symbol;
  winner_symbol := public.ttt_winner(new_board);
  final_status := 'playing';
  final_winner := null;
  next_turn := case when auth.uid() = game.host_id then game.guest_id else game.host_id end;

  if winner_symbol <> '' then
    final_status := 'done';
    final_winner := case when winner_symbol = 'X' then game.host_id else game.guest_id end;
    next_turn := null;
  elsif not ('' = any(new_board)) then
    final_status := 'done';
    next_turn := null;
  end if;

  update public.tic_tac_toe_games
  set board = new_board,
      turn_id = next_turn,
      winner_id = final_winner,
      status = final_status,
      updated_at = now()
  where id = game.id
  returning * into game;

  if final_status = 'done' then
    if final_winner is null then
      perform public.add_points(game.host_id, 25, 35, 'ttt_draw', game.id::text);
      perform public.add_points(game.guest_id, 25, 35, 'ttt_draw', game.id::text);
    else
      perform public.add_points(final_winner, 60, 80, 'ttt_win', game.id::text);
      perform public.add_points(
        case when final_winner = game.host_id then game.guest_id else game.host_id end,
        15,
        20,
        'ttt_loss',
        game.id::text
      );
    end if;
  end if;

  return game;
end;
$$;

create index if not exists user_missions_user_idx on public.user_missions (user_id);
create index if not exists tic_tac_toe_games_code_idx on public.tic_tac_toe_games (code);
create index if not exists tic_tac_toe_games_players_idx on public.tic_tac_toe_games (host_id, guest_id);

grant select on public.user_missions to authenticated;
grant select on public.tic_tac_toe_games to authenticated;

revoke all on function public.equip_shop_item(text) from public, anon;
revoke all on function public.get_my_missions() from public, anon;
revoke all on function public.claim_mission(text) from public, anon;
revoke all on function public.ttt_winner(text[]) from public, anon, authenticated;
revoke all on function public.create_ttt_game() from public, anon;
revoke all on function public.join_ttt_game(text) from public, anon;
revoke all on function public.play_ttt_move(uuid, integer) from public, anon;

grant execute on function public.equip_shop_item(text) to authenticated;
grant execute on function public.get_my_missions() to authenticated;
grant execute on function public.claim_mission(text) to authenticated;
grant execute on function public.create_ttt_game() to authenticated;
grant execute on function public.join_ttt_game(text) to authenticated;
grant execute on function public.play_ttt_move(uuid, integer) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.tic_tac_toe_games;
exception
  when duplicate_object then null;
  when undefined_object then null;
end;
$$;
-- Arcade v3 : succes permanents et centre de notifications.
create table if not exists public.user_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_key text not null,
  unlocked_at timestamptz not null default now(),
  primary key (user_id, achievement_key)
);

create table if not exists public.user_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null default 'system',
  title text not null,
  body text not null default '',
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.user_achievements enable row level security;
alter table public.user_notifications enable row level security;

drop policy if exists "Les utilisateurs lisent leurs succes" on public.user_achievements;
drop policy if exists "Les utilisateurs lisent leurs notifications" on public.user_notifications;
drop policy if exists "Les utilisateurs marquent leurs notifications" on public.user_notifications;

create policy "Les utilisateurs lisent leurs succes"
on public.user_achievements
for select
to authenticated
using (user_id = auth.uid());

create policy "Les utilisateurs lisent leurs notifications"
on public.user_notifications
for select
to authenticated
using (user_id = auth.uid());

create policy "Les utilisateurs marquent leurs notifications"
on public.user_notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.create_notification(
  target_user uuid,
  kind_text text,
  title_text text,
  body_text text default '',
  payload_json jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_user is null then
    return;
  end if;

  insert into public.user_notifications (user_id, kind, title, body, payload)
  values (
    target_user,
    left(coalesce(kind_text, 'system'), 32),
    left(coalesce(title_text, 'Notification'), 80),
    left(coalesce(body_text, ''), 240),
    coalesce(payload_json, '{}'::jsonb)
  );
end;
$$;

create or replace function public.get_my_achievements()
returns table (
  achievement_key text,
  title_text text,
  description_text text,
  icon_text text,
  reward_points integer,
  progress_value integer,
  goal_value integer,
  unlocked boolean,
  unlocked_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with stats as (
    select
      (select count(*)::integer from public.chat_messages where user_id = auth.uid()::text) as messages_count,
      (select count(*)::integer from public.game_scores where user_id = auth.uid()) as games_count,
      (select count(distinct game_key)::integer from public.game_scores where user_id = auth.uid()) as distinct_games,
      (select coalesce(max(score), 0)::integer from public.game_scores where user_id = auth.uid()) as best_score,
      (select count(*)::integer from public.user_inventory where user_id = auth.uid()) as inventory_count,
      (select coalesce(max(level), 1)::integer from public.user_wallets where user_id = auth.uid()) as current_level,
      (select coalesce(max(streak), 0)::integer from public.user_wallets where user_id = auth.uid()) as daily_streak,
      (select count(*)::integer from public.game_duels where (host_id = auth.uid() or guest_id = auth.uid()) and status = 'done')
        + (select count(*)::integer from public.tic_tac_toe_games where (host_id = auth.uid() or guest_id = auth.uid()) and status = 'done') as multi_count
  ), achievements as (
    select 'first_message'::text as achievement_key, 'Premier message'::text as title_text, 'Envoyer ton premier message dans le tchat.'::text as description_text, 'MSG'::text as icon_text, 60::integer as reward_points, messages_count as progress_value, 1::integer as goal_value from stats
    union all select 'first_game', 'Premiere partie', 'Terminer ton premier mini-jeu solo.', 'PLAY', 80, games_count, 1 from stats
    union all select 'first_purchase', 'Premier achat', 'Acheter ton premier item boutique.', 'SHOP', 80, inventory_count, 1 from stats
    union all select 'first_multi', 'Premier multi', 'Terminer un duel ou un morpion en ligne.', 'PVP', 120, multi_count, 1 from stats
    union all select 'score_legend', 'Score legendaire', 'Atteindre 2500 points sur un mini-jeu.', 'TOP', 220, best_score, 2500 from stats
    union all select 'collector', 'Collectionneur', 'Posseder 5 items dans ton inventaire.', 'BAG', 180, inventory_count, 5 from stats
    union all select 'daily_3', 'Joueur quotidien', 'Atteindre 3 jours de streak daily.', 'DAY', 150, daily_streak, 3 from stats
    union all select 'level_5', 'Niveau 5', 'Atteindre le niveau 5.', 'LV5', 180, current_level, 5 from stats
    union all select 'level_10', 'Niveau 10', 'Atteindre le niveau 10.', 'LV10', 350, current_level, 10 from stats
    union all select 'chatter_25', 'Voix du serveur', 'Envoyer 25 messages.', 'CHAT', 200, messages_count, 25 from stats
    union all select 'three_games', 'Explorateur arcade', 'Jouer a 3 jeux differents.', '3G', 160, distinct_games, 3 from stats
  )
  select
    achievements.achievement_key,
    achievements.title_text,
    achievements.description_text,
    achievements.icon_text,
    achievements.reward_points,
    least(achievements.progress_value, achievements.goal_value),
    achievements.goal_value,
    user_achievements.user_id is not null as unlocked,
    user_achievements.unlocked_at
  from achievements
  left join public.user_achievements
    on user_achievements.user_id = auth.uid()
   and user_achievements.achievement_key = achievements.achievement_key
  order by unlocked, achievements.reward_points, achievements.achievement_key;
$$;

create or replace function public.claim_achievement(achievement_key_input text)
returns public.user_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_key text;
  achievement record;
  wallet public.user_wallets;
begin
  clean_key := lower(trim(coalesce(achievement_key_input, '')));

  select *
  into achievement
  from public.get_my_achievements()
  where achievement_key = clean_key;

  if not found then
    raise exception 'achievement_not_found';
  end if;

  if achievement.unlocked then
    raise exception 'achievement_already_unlocked';
  end if;

  if achievement.progress_value < achievement.goal_value then
    raise exception 'achievement_not_ready';
  end if;

  insert into public.user_achievements (user_id, achievement_key)
  values (auth.uid(), clean_key)
  on conflict do nothing;

  if not found then
    raise exception 'achievement_already_unlocked';
  end if;

  wallet := public.add_points(auth.uid(), achievement.reward_points, achievement.reward_points * 2, 'achievement', clean_key);
  perform public.create_notification(
    auth.uid(),
    'achievement',
    'Succes debloque',
    achievement.title_text || ' +' || achievement.reward_points || ' coins',
    jsonb_build_object('achievement_key', clean_key)
  );

  return wallet;
end;
$$;

create or replace function public.get_my_notifications(limit_count integer default 20)
returns setof public.user_notifications
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.user_notifications
  where user_id = auth.uid()
  order by created_at desc
  limit greatest(1, least(coalesce(limit_count, 20), 50));
$$;

create or replace function public.mark_notification_read(notification_id uuid)
returns public.user_notifications
language plpgsql
security definer
set search_path = public
as $$
declare
  notification public.user_notifications;
begin
  update public.user_notifications
  set read_at = coalesce(read_at, now())
  where id = notification_id
    and user_id = auth.uid()
  returning * into notification;

  if notification.id is null then
    raise exception 'notification_not_found';
  end if;

  return notification;
end;
$$;

create index if not exists user_achievements_user_idx on public.user_achievements (user_id);
create index if not exists user_notifications_user_created_idx on public.user_notifications (user_id, created_at desc);
create index if not exists user_notifications_unread_idx on public.user_notifications (user_id, read_at) where read_at is null;

grant select on public.user_achievements to authenticated;
grant select, update on public.user_notifications to authenticated;

revoke all on function public.create_notification(uuid, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.get_my_achievements() from public, anon;
revoke all on function public.claim_achievement(text) from public, anon;
revoke all on function public.get_my_notifications(integer) from public, anon;
revoke all on function public.mark_notification_read(uuid) from public, anon;

grant execute on function public.get_my_achievements() to authenticated;
grant execute on function public.claim_achievement(text) to authenticated;
grant execute on function public.get_my_notifications(integer) to authenticated;
grant execute on function public.mark_notification_read(uuid) to authenticated;