-- A copier dans Supabase > SQL Editor > New query > Run.
-- Ce script active les vrais comptes Supabase et le tchat securise.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  pseudo text not null check (char_length(pseudo) between 3 and 20),
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Les utilisateurs lisent leur profil" on public.profiles;
drop policy if exists "Les utilisateurs creent leur profil" on public.profiles;
drop policy if exists "Les utilisateurs modifient leur profil" on public.profiles;

create policy "Les utilisateurs lisent leur profil"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Les utilisateurs creent leur profil"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "Les utilisateurs modifient leur profil"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_pseudo text;
begin
  requested_pseudo := nullif(trim(new.raw_user_meta_data->>'pseudo'), '');

  insert into public.profiles (id, pseudo, email)
  values (
    new.id,
    coalesce(requested_pseudo, 'Player_' || left(new.id::text, 8)),
    coalesce(new.email, '')
  )
  on conflict (id) do update
  set
    pseudo = excluded.pseudo,
    email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  pseudo text not null check (char_length(pseudo) between 3 and 20),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "Tout le monde peut lire le tchat" on public.chat_messages;
drop policy if exists "Les visiteurs peuvent envoyer un message" on public.chat_messages;
drop policy if exists "Les utilisateurs connectes lisent le tchat" on public.chat_messages;
drop policy if exists "Les utilisateurs connectes envoient un message" on public.chat_messages;

create policy "Les utilisateurs connectes lisent le tchat"
on public.chat_messages
for select
to authenticated
using (true);

create policy "Les utilisateurs connectes envoient un message"
on public.chat_messages
for insert
to authenticated
with check (
  user_id = auth.uid()::text
  and char_length(pseudo) between 3 and 20
  and char_length(content) between 1 and 500
);

create index if not exists chat_messages_created_at_idx
on public.chat_messages (created_at desc);

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.chat_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end;
$$;
