-- A copier dans Supabase > SQL Editor > New query > Run.
-- Cette version simple fonctionne avec GitHub Pages et le login local du site.
-- Pour une vraie production, remplace le login local par Supabase Auth.

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id text not null,
  pseudo text not null check (char_length(pseudo) between 3 and 20),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.chat_messages enable row level security;

drop policy if exists "Tout le monde peut lire le tchat" on public.chat_messages;
drop policy if exists "Les visiteurs peuvent envoyer un message" on public.chat_messages;

create policy "Tout le monde peut lire le tchat"
on public.chat_messages
for select
to anon, authenticated
using (true);

create policy "Les visiteurs peuvent envoyer un message"
on public.chat_messages
for insert
to anon, authenticated
with check (
  char_length(user_id) >= 8
  and char_length(pseudo) between 3 and 20
  and char_length(content) between 1 and 500
);

create index if not exists chat_messages_created_at_idx
on public.chat_messages (created_at desc);
